// api/plan/weekly/generate.js
// §3.11 Weekly skeleton: 0-token DeadlinePlanner draft → small AI summary call
// (~600 tokens). Standard serverless runtime (not Edge — no SSE needed).
//
// Output: persists week_plans row with skeleton + insight.

import { createClient } from "@supabase/supabase-js";
import { planByDeadlines } from "../../_lib/deadlinePlanner.js";
import { generateBuffered } from "../../_lib/aiProviderManager.js";

function mondayOf(date = new Date()) {
  const d = new Date(date);
  const day = d.getUTCDay();
  const diff = (day + 6) % 7;
  d.setUTCDate(d.getUTCDate() - diff);
  d.setUTCHours(0, 0, 0, 0);
  return d.toISOString().slice(0, 10);
}

export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).end("Method Not Allowed");
  const token = (req.headers.authorization || "").replace(/^Bearer\s+/i, "");
  if (!token) return res.status(401).end("Unauthorized");

  const admin = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, {
    auth: { persistSession: false },
  });
  const { data: ures, error: uErr } = await admin.auth.getUser(token);
  if (uErr || !ures?.user) return res.status(401).end("Unauthorized");
  const userId = ures.user.id;

  const { data: profile } = await admin.from("profiles").select("daily_hour_cap, ai_data_consent").eq("id", userId).single();
  const { data: tasks } = await admin.from("tasks").select("*")
    .eq("user_id", userId).in("status", ["inbox", "scheduled"]);

  const flex = (tasks ?? []).filter((t) => !t.is_fixed && t.deadline);
  const { perDay, overflowTaskIds } = planByDeadlines(flex, profile?.daily_hour_cap ?? 8);

  // §3.11 lightweight AI summary (consent-gated)
  let insight = "Skeleton generated by deadline planner.";
  let loadScore = 0;
  const dayLoads = Object.values(perDay).map((arr) => arr.reduce((s, x) => s + x.hours, 0));
  if (dayLoads.length) loadScore = +(dayLoads.reduce((a, b) => a + b, 0) / dayLoads.length / (profile?.daily_hour_cap ?? 8)).toFixed(2);

  if (profile?.ai_data_consent) {
    const { text } = await generateBuffered({
      system: "One-paragraph weekly insight (<=60 words). Concise, encouraging, calls out risk days. Plain text only.",
      user: JSON.stringify({ perDay, overflowTaskIds, dailyHourCap: profile?.daily_hour_cap }),
    });
    if (text) insight = text.trim().slice(0, 600);
  }

  const weekStart = mondayOf();
  await admin.from("week_plans").upsert({
    user_id: userId, week_start: weekStart,
    skeleton: { perDay, overflowTaskIds },
    load_score: loadScore, insight,
  }, { onConflict: "user_id,week_start" });

  res.status(200).json({ week_start: weekStart, perDay, overflowTaskIds, insight, load_score: loadScore });
}
